export const IPC = {
  selectMediaFiles: 'media:selectFiles',
  selectAudioFiles: 'media:selectAudioFiles',
  probeMedia: 'media:probe',
  generateThumbnail: 'media:thumbnail',
  generateFrame: 'media:frame',
  generateWaveform: 'media:waveform',
  detectSilence: 'media:detectSilence',
  detectHighlights: 'media:detectHighlights',
  transcribe: 'media:transcribe',
  transcribeWords: 'media:transcribeWords',
  voicevoxListSpeakers: 'voicevox:listSpeakers',
  voicevoxSynthesize: 'voicevox:synthesize',
  selectExportPath: 'export:selectPath',
  selectExportFolder: 'export:selectFolder',
  exportProject: 'export:run',
  exportProgress: 'export:progress',
  openExternal: 'shell:openExternal',
  showItemInFolder: 'shell:showItemInFolder',
  openPath: 'shell:openPath',
  selectProjectSavePath: 'project:selectSavePath',
  selectProjectOpenPath: 'project:selectOpenPath',
  saveProject: 'project:save',
  loadProject: 'project:load',
  downloadAudioAsset: 'audioLibrary:download'
} as const
